const defaultWeatherData = {
  location: {
    name: "London",
    region: "City of London, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.11,
    tz_id: "Europe/London",
    localtime_epoch: 1696829785,
    localtime: "2023-10-09 6:36",
  },
  current: {
    last_updated_epoch: 1696829400,
    last_updated: "2023-10-09 06:30",
    temp_c: 13.0,
    temp_f: 55.4,
    is_day: 0,
    condition: {
      text: "Clear",
      icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
      code: 1000,
    },
    wind_mph: 2.2,
    wind_kph: 3.6,
    wind_degree: 320,
    wind_dir: "NW",
    pressure_mb: 1021.0,
    pressure_in: 30.15,
    precip_mm: 0.0,
    precip_in: 0.0,
    humidity: 94,
    cloud: 0,
    feelslike_c: 12.7,
    feelslike_f: 54.8,
    vis_km: 10.0,
    vis_miles: 6.0,
    uv: 1.0,
    gust_mph: 8.9,
    gust_kph: 14.4,
  },
  forecast: {
    forecastday: [
      {
        date: "2023-10-09",
        date_epoch: 1696809600,
        day: {
          maxtemp_c: 22.7,
          maxtemp_f: 72.8,
          mintemp_c: 14.4,
          mintemp_f: 57.9,
          avgtemp_c: 17.9,
          avgtemp_f: 64.2,
          maxwind_mph: 6.3,
          maxwind_kph: 10.1,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 66.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
            code: 1003,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: "07:14 AM",
          sunset: "06:21 PM",
          moonrise: "12:54 AM",
          moonset: "05:09 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "28",
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1696806000,
            time: "2023-10-09 00:00",
            temp_c: 15.3,
            temp_f: 59.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1026.0,
            pressure_in: 30.29,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 45,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 15.3,
            heatindex_f: 59.5,
            dewpoint_c: 12.2,
            dewpoint_f: 53.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.6,
            gust_kph: 9.0,
            uv: 1.0,
          },
          {
            time_epoch: 1696809600,
            time: "2023-10-09 01:00",
            temp_c: 15.1,
            temp_f: 59.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1026.0,
            pressure_in: 30.28,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 85,
            cloud: 43,
            feelslike_c: 15.1,
            feelslike_f: 59.1,
            windchill_c: 15.1,
            windchill_f: 59.1,
            heatindex_c: 15.1,
            heatindex_f: 59.1,
            dewpoint_c: 12.6,
            dewpoint_f: 54.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.6,
            gust_kph: 10.6,
            uv: 1.0,
          },
          {
            time_epoch: 1696813200,
            time: "2023-10-09 02:00",
            temp_c: 14.9,
            temp_f: 58.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 1025.0,
            pressure_in: 30.26,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 44,
            feelslike_c: 15.1,
            feelslike_f: 59.1,
            windchill_c: 15.1,
            windchill_f: 59.1,
            heatindex_c: 14.9,
            heatindex_f: 58.9,
            dewpoint_c: 13.0,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 1.0,
          },
          {
            time_epoch: 1696816800,
            time: "2023-10-09 03:00",
            temp_c: 14.9,
            temp_f: 58.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 237,
            wind_dir: "WSW",
            pressure_mb: 1025.0,
            pressure_in: 30.25,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 88,
            cloud: 49,
            feelslike_c: 15.0,
            feelslike_f: 59.0,
            windchill_c: 15.0,
            windchill_f: 59.0,
            heatindex_c: 14.9,
            heatindex_f: 58.8,
            dewpoint_c: 13.0,
            dewpoint_f: 55.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.6,
            gust_kph: 12.2,
            uv: 1.0,
          },
          {
            time_epoch: 1696820400,
            time: "2023-10-09 04:00",
            temp_c: 14.7,
            temp_f: 58.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 234,
            wind_dir: "SW",
            pressure_mb: 1024.0,
            pressure_in: 30.24,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 87,
            cloud: 47,
            feelslike_c: 14.8,
            feelslike_f: 58.7,
            windchill_c: 14.8,
            windchill_f: 58.7,
            heatindex_c: 14.7,
            heatindex_f: 58.5,
            dewpoint_c: 12.7,
            dewpoint_f: 54.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.7,
            gust_kph: 12.3,
            uv: 1.0,
          },
          {
            time_epoch: 1696824000,
            time: "2023-10-09 05:00",
            temp_c: 14.6,
            temp_f: 58.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1024.0,
            pressure_in: 30.24,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 86,
            cloud: 28,
            feelslike_c: 14.6,
            feelslike_f: 58.3,
            windchill_c: 14.6,
            windchill_f: 58.3,
            heatindex_c: 14.6,
            heatindex_f: 58.3,
            dewpoint_c: 12.3,
            dewpoint_f: 54.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.2,
            gust_kph: 13.2,
            uv: 1.0,
          },
          {
            time_epoch: 1696827600,
            time: "2023-10-09 06:00",
            temp_c: 13.0,
            temp_f: 55.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 320,
            wind_dir: "NW",
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 94,
            cloud: 0,
            feelslike_c: 14.3,
            feelslike_f: 57.7,
            windchill_c: 14.3,
            windchill_f: 57.7,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            dewpoint_c: 12.0,
            dewpoint_f: 53.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.9,
            gust_kph: 14.4,
            uv: 1.0,
          },
          {
            time_epoch: 1696831200,
            time: "2023-10-09 07:00",
            temp_c: 14.6,
            temp_f: 58.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 242,
            wind_dir: "WSW",
            pressure_mb: 1024.0,
            pressure_in: 30.24,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 82,
            cloud: 45,
            feelslike_c: 14.6,
            feelslike_f: 58.3,
            windchill_c: 14.6,
            windchill_f: 58.3,
            heatindex_c: 14.6,
            heatindex_f: 58.3,
            dewpoint_c: 11.7,
            dewpoint_f: 53.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.1,
            gust_kph: 13.1,
            uv: 1.0,
          },
          {
            time_epoch: 1696834800,
            time: "2023-10-09 08:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 255,
            wind_dir: "WSW",
            pressure_mb: 1024.0,
            pressure_in: 30.25,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 74,
            cloud: 30,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            windchill_c: 16.0,
            windchill_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            dewpoint_c: 11.4,
            dewpoint_f: 52.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.5,
            gust_kph: 10.4,
            uv: 5.0,
          },
          {
            time_epoch: 1696838400,
            time: "2023-10-09 09:00",
            temp_c: 17.3,
            temp_f: 63.1,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 263,
            wind_dir: "W",
            pressure_mb: 1024.0,
            pressure_in: 30.25,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 18,
            feelslike_c: 17.3,
            feelslike_f: 63.1,
            windchill_c: 17.3,
            windchill_f: 63.1,
            heatindex_c: 17.3,
            heatindex_f: 63.1,
            dewpoint_c: 10.9,
            dewpoint_f: 51.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.0,
            gust_kph: 11.2,
            uv: 5.0,
          },
          {
            time_epoch: 1696842000,
            time: "2023-10-09 10:00",
            temp_c: 18.2,
            temp_f: 64.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 273,
            wind_dir: "W",
            pressure_mb: 1024.0,
            pressure_in: 30.24,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 48,
            feelslike_c: 18.2,
            feelslike_f: 64.8,
            windchill_c: 18.2,
            windchill_f: 64.8,
            heatindex_c: 18.2,
            heatindex_f: 64.8,
            dewpoint_c: 10.5,
            dewpoint_f: 51.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.2,
            gust_kph: 13.2,
            uv: 5.0,
          },
          {
            time_epoch: 1696845600,
            time: "2023-10-09 11:00",
            temp_c: 19.2,
            temp_f: 66.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9.0,
            wind_degree: 263,
            wind_dir: "W",
            pressure_mb: 1024.0,
            pressure_in: 30.23,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 56,
            cloud: 48,
            feelslike_c: 19.2,
            feelslike_f: 66.5,
            windchill_c: 19.2,
            windchill_f: 66.5,
            heatindex_c: 19.2,
            heatindex_f: 66.5,
            dewpoint_c: 10.3,
            dewpoint_f: 50.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.5,
            gust_kph: 12.0,
            uv: 5.0,
          },
          {
            time_epoch: 1696849200,
            time: "2023-10-09 12:00",
            temp_c: 20.7,
            temp_f: 69.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 274,
            wind_dir: "W",
            pressure_mb: 1024.0,
            pressure_in: 30.22,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 50,
            cloud: 48,
            feelslike_c: 20.7,
            feelslike_f: 69.2,
            windchill_c: 20.7,
            windchill_f: 69.2,
            heatindex_c: 20.7,
            heatindex_f: 69.2,
            dewpoint_c: 9.8,
            dewpoint_f: 49.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.7,
            gust_kph: 12.3,
            uv: 6.0,
          },
          {
            time_epoch: 1696852800,
            time: "2023-10-09 13:00",
            temp_c: 21.6,
            temp_f: 70.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.3,
            wind_kph: 10.1,
            wind_degree: 283,
            wind_dir: "WNW",
            pressure_mb: 1023.0,
            pressure_in: 30.21,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 46,
            cloud: 46,
            feelslike_c: 21.6,
            feelslike_f: 70.9,
            windchill_c: 21.6,
            windchill_f: 70.9,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 9.5,
            dewpoint_f: 49.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.0,
            gust_kph: 12.9,
            uv: 6.0,
          },
          {
            time_epoch: 1696856400,
            time: "2023-10-09 14:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 271,
            wind_dir: "W",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 43,
            cloud: 46,
            feelslike_c: 24.3,
            feelslike_f: 75.8,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 24.3,
            heatindex_f: 75.8,
            dewpoint_c: 9.4,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 6.0,
          },
          {
            time_epoch: 1696860000,
            time: "2023-10-09 15:00",
            temp_c: 22.7,
            temp_f: 72.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 6.0,
            wind_kph: 9.7,
            wind_degree: 276,
            wind_dir: "W",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 44,
            cloud: 29,
            feelslike_c: 24.4,
            feelslike_f: 76.0,
            windchill_c: 22.7,
            windchill_f: 72.8,
            heatindex_c: 24.4,
            heatindex_f: 76.0,
            dewpoint_c: 9.9,
            dewpoint_f: 49.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.0,
            gust_kph: 12.9,
            uv: 6.0,
          },
          {
            time_epoch: 1696863600,
            time: "2023-10-09 16:00",
            temp_c: 22.1,
            temp_f: 71.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 276,
            wind_dir: "W",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 47,
            cloud: 21,
            feelslike_c: 24.4,
            feelslike_f: 75.9,
            windchill_c: 22.1,
            windchill_f: 71.8,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 10.4,
            dewpoint_f: 50.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.9,
            gust_kph: 11.1,
            uv: 6.0,
          },
          {
            time_epoch: 1696867200,
            time: "2023-10-09 17:00",
            temp_c: 20.4,
            temp_f: 68.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 254,
            wind_dir: "WSW",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 26,
            feelslike_c: 20.4,
            feelslike_f: 68.7,
            windchill_c: 20.4,
            windchill_f: 68.7,
            heatindex_c: 20.4,
            heatindex_f: 68.7,
            dewpoint_c: 10.6,
            dewpoint_f: 51.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.7,
            gust_kph: 12.3,
            uv: 6.0,
          },
          {
            time_epoch: 1696870800,
            time: "2023-10-09 18:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 269,
            wind_dir: "W",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 23,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 10.7,
            dewpoint_f: 51.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.4,
            gust_kph: 11.9,
            uv: 5.0,
          },
          {
            time_epoch: 1696874400,
            time: "2023-10-09 19:00",
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 257,
            wind_dir: "WSW",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 15,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            windchill_c: 18.9,
            windchill_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            dewpoint_c: 10.7,
            dewpoint_f: 51.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 5.3,
            gust_kph: 8.6,
            uv: 1.0,
          },
          {
            time_epoch: 1696878000,
            time: "2023-10-09 20:00",
            temp_c: 18.6,
            temp_f: 65.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.1,
            wind_kph: 5.0,
            wind_degree: 247,
            wind_dir: "WSW",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 60,
            cloud: 28,
            feelslike_c: 18.6,
            feelslike_f: 65.4,
            windchill_c: 18.6,
            windchill_f: 65.4,
            heatindex_c: 18.6,
            heatindex_f: 65.4,
            dewpoint_c: 10.7,
            dewpoint_f: 51.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 6.2,
            gust_kph: 10.0,
            uv: 1.0,
          },
          {
            time_epoch: 1696881600,
            time: "2023-10-09 21:00",
            temp_c: 18.1,
            temp_f: 64.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 237,
            wind_dir: "WSW",
            pressure_mb: 1022.0,
            pressure_in: 30.19,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 22,
            feelslike_c: 18.1,
            feelslike_f: 64.6,
            windchill_c: 18.1,
            windchill_f: 64.6,
            heatindex_c: 18.1,
            heatindex_f: 64.6,
            dewpoint_c: 10.5,
            dewpoint_f: 51.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.2,
            gust_kph: 11.7,
            uv: 1.0,
          },
          {
            time_epoch: 1696885200,
            time: "2023-10-09 22:00",
            temp_c: 17.6,
            temp_f: 63.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 229,
            wind_dir: "SW",
            pressure_mb: 1022.0,
            pressure_in: 30.18,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 29,
            feelslike_c: 17.6,
            feelslike_f: 63.8,
            windchill_c: 17.6,
            windchill_f: 63.8,
            heatindex_c: 17.6,
            heatindex_f: 63.8,
            dewpoint_c: 10.3,
            dewpoint_f: 50.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.8,
            gust_kph: 12.5,
            uv: 1.0,
          },
          {
            time_epoch: 1696888800,
            time: "2023-10-09 23:00",
            temp_c: 17.2,
            temp_f: 63.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 220,
            wind_dir: "SW",
            pressure_mb: 1022.0,
            pressure_in: 30.17,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 11,
            feelslike_c: 17.2,
            feelslike_f: 63.0,
            windchill_c: 17.2,
            windchill_f: 63.0,
            heatindex_c: 17.2,
            heatindex_f: 63.0,
            dewpoint_c: 10.1,
            dewpoint_f: 50.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.7,
            gust_kph: 14.0,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2023-10-10",
        date_epoch: 1696896000,
        day: {
          maxtemp_c: 24.5,
          maxtemp_f: 76.0,
          mintemp_c: 15.0,
          mintemp_f: 59.0,
          avgtemp_c: 18.9,
          avgtemp_f: 66.1,
          maxwind_mph: 11.4,
          maxwind_kph: 18.4,
          totalprecip_mm: 0.0,
          totalprecip_in: 0.0,
          totalsnow_cm: 0.0,
          avgvis_km: 10.0,
          avgvis_miles: 6.0,
          avghumidity: 56.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Sunny",
            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
            code: 1000,
          },
          uv: 5.0,
        },
        astro: {
          sunrise: "07:16 AM",
          sunset: "06:18 PM",
          moonrise: "02:08 AM",
          moonset: "05:23 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "20",
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1696892400,
            time: "2023-10-10 00:00",
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 214,
            wind_dir: "SW",
            pressure_mb: 1021.0,
            pressure_in: 30.16,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 20,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            windchill_c: 16.8,
            windchill_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            dewpoint_c: 9.9,
            dewpoint_f: 49.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 7.9,
            gust_kph: 12.6,
            uv: 1.0,
          },
          {
            time_epoch: 1696896000,
            time: "2023-10-10 01:00",
            temp_c: 16.4,
            temp_f: 61.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 4.0,
            wind_kph: 6.5,
            wind_degree: 213,
            wind_dir: "SSW",
            pressure_mb: 1021.0,
            pressure_in: 30.15,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 29,
            feelslike_c: 16.4,
            feelslike_f: 61.4,
            windchill_c: 16.4,
            windchill_f: 61.4,
            heatindex_c: 16.4,
            heatindex_f: 61.4,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 8.4,
            gust_kph: 13.5,
            uv: 1.0,
          },
          {
            time_epoch: 1696899600,
            time: "2023-10-10 02:00",
            temp_c: 15.9,
            temp_f: 60.7,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 1021.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 6,
            feelslike_c: 15.9,
            feelslike_f: 60.7,
            windchill_c: 15.9,
            windchill_f: 60.7,
            heatindex_c: 15.9,
            heatindex_f: 60.7,
            dewpoint_c: 9.5,
            dewpoint_f: 49.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.3,
            gust_kph: 14.9,
            uv: 1.0,
          },
          {
            time_epoch: 1696903200,
            time: "2023-10-10 03:00",
            temp_c: 15.6,
            temp_f: 60.1,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1020.0,
            pressure_in: 30.14,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 8,
            feelslike_c: 15.6,
            feelslike_f: 60.2,
            windchill_c: 15.6,
            windchill_f: 60.2,
            heatindex_c: 15.6,
            heatindex_f: 60.2,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.1,
            gust_kph: 14.7,
            uv: 1.0,
          },
          {
            time_epoch: 1696906800,
            time: "2023-10-10 04:00",
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 222,
            wind_dir: "SW",
            pressure_mb: 1020.0,
            pressure_in: 30.12,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 8,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            windchill_c: 15.5,
            windchill_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            dewpoint_c: 9.2,
            dewpoint_f: 48.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.9,
            gust_kph: 16.0,
            uv: 1.0,
          },
          {
            time_epoch: 1696910400,
            time: "2023-10-10 05:00",
            temp_c: 15.3,
            temp_f: 59.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 4.7,
            wind_kph: 7.6,
            wind_degree: 223,
            wind_dir: "SW",
            pressure_mb: 1020.0,
            pressure_in: 30.11,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 6,
            feelslike_c: 15.3,
            feelslike_f: 59.5,
            windchill_c: 15.3,
            windchill_f: 59.5,
            heatindex_c: 15.3,
            heatindex_f: 59.5,
            dewpoint_c: 9.1,
            dewpoint_f: 48.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 9.5,
            gust_kph: 15.3,
            uv: 1.0,
          },
          {
            time_epoch: 1696914000,
            time: "2023-10-10 06:00",
            temp_c: 15.0,
            temp_f: 59.0,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 67,
            cloud: 5,
            feelslike_c: 15.0,
            feelslike_f: 59.0,
            windchill_c: 15.0,
            windchill_f: 59.0,
            heatindex_c: 15.0,
            heatindex_f: 59.0,
            dewpoint_c: 8.9,
            dewpoint_f: 48.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 17.0,
            uv: 1.0,
          },
          {
            time_epoch: 1696917600,
            time: "2023-10-10 07:00",
            temp_c: 15.2,
            temp_f: 59.4,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 219,
            wind_dir: "SW",
            pressure_mb: 1019.0,
            pressure_in: 30.09,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 6,
            feelslike_c: 15.2,
            feelslike_f: 59.4,
            windchill_c: 15.2,
            windchill_f: 59.4,
            heatindex_c: 15.2,
            heatindex_f: 59.4,
            dewpoint_c: 8.8,
            dewpoint_f: 47.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.6,
            gust_kph: 17.0,
            uv: 1.0,
          },
          {
            time_epoch: 1696921200,
            time: "2023-10-10 08:00",
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 5.8,
            wind_kph: 9.4,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1019.0,
            pressure_in: 30.08,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 60,
            cloud: 8,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 8.7,
            dewpoint_f: 47.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.1,
            gust_kph: 16.2,
            uv: 5.0,
          },
          {
            time_epoch: 1696924800,
            time: "2023-10-10 09:00",
            temp_c: 17.9,
            temp_f: 64.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 7.2,
            wind_kph: 11.5,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1018.0,
            pressure_in: 30.07,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 8,
            feelslike_c: 17.9,
            feelslike_f: 64.3,
            windchill_c: 17.9,
            windchill_f: 64.3,
            heatindex_c: 17.9,
            heatindex_f: 64.3,
            dewpoint_c: 8.9,
            dewpoint_f: 48.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.5,
            gust_kph: 16.9,
            uv: 5.0,
          },
          {
            time_epoch: 1696928400,
            time: "2023-10-10 10:00",
            temp_c: 19.3,
            temp_f: 66.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 8.1,
            wind_kph: 13.0,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1018.0,
            pressure_in: 30.06,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 8,
            feelslike_c: 19.3,
            feelslike_f: 66.8,
            windchill_c: 19.3,
            windchill_f: 66.8,
            heatindex_c: 19.3,
            heatindex_f: 66.8,
            dewpoint_c: 9.3,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 10.7,
            gust_kph: 17.2,
            uv: 5.0,
          },
          {
            time_epoch: 1696932000,
            time: "2023-10-10 11:00",
            temp_c: 21.1,
            temp_f: 70.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 233,
            wind_dir: "SW",
            pressure_mb: 1017.0,
            pressure_in: 30.04,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 48,
            cloud: 9,
            feelslike_c: 21.1,
            feelslike_f: 70.1,
            windchill_c: 21.1,
            windchill_f: 70.1,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 9.6,
            dewpoint_f: 49.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 12.0,
            gust_kph: 19.3,
            uv: 6.0,
          },
          {
            time_epoch: 1696935600,
            time: "2023-10-10 12:00",
            temp_c: 22.7,
            temp_f: 72.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 237,
            wind_dir: "WSW",
            pressure_mb: 1017.0,
            pressure_in: 30.02,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 42,
            cloud: 5,
            feelslike_c: 24.4,
            feelslike_f: 75.8,
            windchill_c: 22.7,
            windchill_f: 72.9,
            heatindex_c: 24.4,
            heatindex_f: 75.8,
            dewpoint_c: 9.3,
            dewpoint_f: 48.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.3,
            gust_kph: 21.3,
            uv: 6.0,
          },
          {
            time_epoch: 1696939200,
            time: "2023-10-10 13:00",
            temp_c: 24.1,
            temp_f: 75.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1016.0,
            pressure_in: 30.0,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 38,
            cloud: 7,
            feelslike_c: 24.7,
            feelslike_f: 76.4,
            windchill_c: 24.1,
            windchill_f: 75.3,
            heatindex_c: 24.7,
            heatindex_f: 76.4,
            dewpoint_c: 8.8,
            dewpoint_f: 47.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.0,
            gust_kph: 22.5,
            uv: 6.0,
          },
          {
            time_epoch: 1696942800,
            time: "2023-10-10 14:00",
            temp_c: 24.5,
            temp_f: 76.0,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 11.0,
            wind_kph: 17.6,
            wind_degree: 241,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.98,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 37,
            cloud: 9,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 24.5,
            windchill_f: 76.0,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 9.0,
            dewpoint_f: 48.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.6,
            gust_kph: 22.0,
            uv: 6.0,
          },
          {
            time_epoch: 1696946400,
            time: "2023-10-10 15:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 39,
            cloud: 9,
            feelslike_c: 24.8,
            feelslike_f: 76.6,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 24.8,
            heatindex_f: 76.6,
            dewpoint_c: 9.4,
            dewpoint_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.1,
            gust_kph: 22.7,
            uv: 6.0,
          },
          {
            time_epoch: 1696950000,
            time: "2023-10-10 16:00",
            temp_c: 23.2,
            temp_f: 73.8,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 240,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 42,
            cloud: 8,
            feelslike_c: 24.5,
            feelslike_f: 76.2,
            windchill_c: 23.2,
            windchill_f: 73.8,
            heatindex_c: 24.5,
            heatindex_f: 76.2,
            dewpoint_c: 9.7,
            dewpoint_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.3,
            gust_kph: 24.6,
            uv: 6.0,
          },
          {
            time_epoch: 1696953600,
            time: "2023-10-10 17:00",
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 242,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 47,
            cloud: 8,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 10.1,
            dewpoint_f: 50.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.5,
            uv: 6.0,
          },
          {
            time_epoch: 1696957200,
            time: "2023-10-10 18:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 241,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 14,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 10.7,
            dewpoint_f: 51.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.4,
            gust_kph: 24.8,
            uv: 6.0,
          },
          {
            time_epoch: 1696960800,
            time: "2023-10-10 19:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 58,
            cloud: 17,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 11.5,
            dewpoint_f: 52.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1696964400,
            time: "2023-10-10 20:00",
            temp_c: 19.2,
            temp_f: 66.6,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.7,
            wind_kph: 17.3,
            wind_degree: 249,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 15,
            feelslike_c: 19.2,
            feelslike_f: 66.6,
            windchill_c: 19.2,
            windchill_f: 66.6,
            heatindex_c: 19.2,
            heatindex_f: 66.6,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.4,
            gust_kph: 26.5,
            uv: 1.0,
          },
          {
            time_epoch: 1696968000,
            time: "2023-10-10 21:00",
            temp_c: 18.6,
            temp_f: 65.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.5,
            wind_kph: 16.9,
            wind_degree: 248,
            wind_dir: "WSW",
            pressure_mb: 1015.0,
            pressure_in: 29.97,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 19,
            feelslike_c: 18.6,
            feelslike_f: 65.5,
            windchill_c: 18.6,
            windchill_f: 65.5,
            heatindex_c: 18.6,
            heatindex_f: 65.5,
            dewpoint_c: 11.3,
            dewpoint_f: 52.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.1,
            gust_kph: 25.9,
            uv: 1.0,
          },
          {
            time_epoch: 1696971600,
            time: "2023-10-10 22:00",
            temp_c: 18.0,
            temp_f: 64.5,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 243,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.96,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 17,
            feelslike_c: 18.0,
            feelslike_f: 64.5,
            windchill_c: 18.0,
            windchill_f: 64.5,
            heatindex_c: 18.0,
            heatindex_f: 64.5,
            dewpoint_c: 11.3,
            dewpoint_f: 52.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.0,
            gust_kph: 24.1,
            uv: 1.0,
          },
          {
            time_epoch: 1696975200,
            time: "2023-10-10 23:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 0,
            condition: {
              text: "Clear",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.95,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 18,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            windchill_c: 17.7,
            windchill_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            dewpoint_c: 11.2,
            dewpoint_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.3,
            uv: 1.0,
          },
        ],
      },
      {
        date: "2023-10-11",
        date_epoch: 1696982400,
        day: {
          maxtemp_c: 22.2,
          maxtemp_f: 71.9,
          mintemp_c: 13.0,
          mintemp_f: 55.4,
          avgtemp_c: 17.9,
          avgtemp_f: 64.1,
          maxwind_mph: 15.4,
          maxwind_kph: 24.8,
          totalprecip_mm: 2.26,
          totalprecip_in: 0.09,
          totalsnow_cm: 0.0,
          avgvis_km: 9.5,
          avgvis_miles: 5.0,
          avghumidity: 64.0,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 53,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 4.0,
        },
        astro: {
          sunrise: "07:17 AM",
          sunset: "06:16 PM",
          moonrise: "03:20 AM",
          moonset: "05:35 PM",
          moon_phase: "Waning Crescent",
          moon_illumination: "13",
          is_moon_up: 0,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1696978800,
            time: "2023-10-11 00:00",
            temp_c: 17.5,
            temp_f: 63.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 246,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.94,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 45,
            feelslike_c: 17.5,
            feelslike_f: 63.4,
            windchill_c: 17.5,
            windchill_f: 63.4,
            heatindex_c: 17.5,
            heatindex_f: 63.4,
            dewpoint_c: 11.0,
            dewpoint_f: 51.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.2,
            gust_kph: 24.5,
            uv: 1.0,
          },
          {
            time_epoch: 1696982400,
            time: "2023-10-11 01:00",
            temp_c: 17.2,
            temp_f: 63.0,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.2,
            wind_kph: 14.8,
            wind_degree: 242,
            wind_dir: "WSW",
            pressure_mb: 1014.0,
            pressure_in: 29.93,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 66,
            cloud: 46,
            feelslike_c: 17.2,
            feelslike_f: 63.0,
            windchill_c: 17.2,
            windchill_f: 63.0,
            heatindex_c: 17.2,
            heatindex_f: 63.0,
            dewpoint_c: 10.8,
            dewpoint_f: 51.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.4,
            gust_kph: 23.2,
            uv: 1.0,
          },
          {
            time_epoch: 1696986000,
            time: "2023-10-11 02:00",
            temp_c: 17.1,
            temp_f: 62.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 239,
            wind_dir: "WSW",
            pressure_mb: 1013.0,
            pressure_in: 29.92,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 65,
            cloud: 45,
            feelslike_c: 17.1,
            feelslike_f: 62.7,
            windchill_c: 17.1,
            windchill_f: 62.7,
            heatindex_c: 17.1,
            heatindex_f: 62.7,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.2,
            gust_kph: 22.9,
            uv: 1.0,
          },
          {
            time_epoch: 1696989600,
            time: "2023-10-11 03:00",
            temp_c: 17.0,
            temp_f: 62.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.5,
            wind_kph: 13.7,
            wind_degree: 227,
            wind_dir: "SW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 64,
            cloud: 49,
            feelslike_c: 17.0,
            feelslike_f: 62.5,
            windchill_c: 17.0,
            windchill_f: 62.5,
            heatindex_c: 17.0,
            heatindex_f: 62.5,
            dewpoint_c: 10.1,
            dewpoint_f: 50.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 13.8,
            gust_kph: 22.2,
            uv: 1.0,
          },
          {
            time_epoch: 1696993200,
            time: "2023-10-11 04:00",
            temp_c: 17.0,
            temp_f: 62.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 244,
            wind_dir: "WSW",
            pressure_mb: 1012.0,
            pressure_in: 29.9,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 46,
            feelslike_c: 17.0,
            feelslike_f: 62.6,
            windchill_c: 17.0,
            windchill_f: 62.6,
            heatindex_c: 17.0,
            heatindex_f: 62.6,
            dewpoint_c: 9.9,
            dewpoint_f: 49.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 14.4,
            gust_kph: 23.2,
            uv: 1.0,
          },
          {
            time_epoch: 1696996800,
            time: "2023-10-11 05:00",
            temp_c: 17.0,
            temp_f: 62.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.6,
            wind_kph: 15.5,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1012.0,
            pressure_in: 29.89,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 62,
            cloud: 41,
            feelslike_c: 17.0,
            feelslike_f: 62.6,
            windchill_c: 17.0,
            windchill_f: 62.6,
            heatindex_c: 17.0,
            heatindex_f: 62.6,
            dewpoint_c: 9.8,
            dewpoint_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.3,
            gust_kph: 24.6,
            uv: 1.0,
          },
          {
            time_epoch: 1697000400,
            time: "2023-10-11 06:00",
            temp_c: 16.9,
            temp_f: 62.4,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 9.4,
            wind_kph: 15.1,
            wind_degree: 218,
            wind_dir: "SW",
            pressure_mb: 1011.0,
            pressure_in: 29.87,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 63,
            cloud: 45,
            feelslike_c: 16.9,
            feelslike_f: 62.4,
            windchill_c: 16.9,
            windchill_f: 62.4,
            heatindex_c: 16.9,
            heatindex_f: 62.4,
            dewpoint_c: 9.8,
            dewpoint_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 15.7,
            gust_kph: 25.2,
            uv: 1.0,
          },
          {
            time_epoch: 1697004000,
            time: "2023-10-11 07:00",
            temp_c: 17.6,
            temp_f: 63.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 10.3,
            wind_kph: 16.6,
            wind_degree: 221,
            wind_dir: "SW",
            pressure_mb: 1011.0,
            pressure_in: 29.86,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 61,
            cloud: 42,
            feelslike_c: 17.6,
            feelslike_f: 63.7,
            windchill_c: 17.6,
            windchill_f: 63.7,
            heatindex_c: 17.6,
            heatindex_f: 63.7,
            dewpoint_c: 10.0,
            dewpoint_f: 50.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.1,
            gust_kph: 25.9,
            uv: 1.0,
          },
          {
            time_epoch: 1697007600,
            time: "2023-10-11 08:00",
            temp_c: 18.4,
            temp_f: 65.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 11.4,
            wind_kph: 18.4,
            wind_degree: 224,
            wind_dir: "SW",
            pressure_mb: 1011.0,
            pressure_in: 29.85,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 59,
            cloud: 40,
            feelslike_c: 18.4,
            feelslike_f: 65.1,
            windchill_c: 18.4,
            windchill_f: 65.1,
            heatindex_c: 18.4,
            heatindex_f: 65.1,
            dewpoint_c: 10.3,
            dewpoint_f: 50.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.6,
            gust_kph: 26.6,
            uv: 5.0,
          },
          {
            time_epoch: 1697011200,
            time: "2023-10-11 09:00",
            temp_c: 19.1,
            temp_f: 66.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 12.3,
            wind_kph: 19.8,
            wind_degree: 226,
            wind_dir: "SW",
            pressure_mb: 1011.0,
            pressure_in: 29.84,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 57,
            cloud: 38,
            feelslike_c: 19.1,
            feelslike_f: 66.4,
            windchill_c: 19.1,
            windchill_f: 66.4,
            heatindex_c: 19.1,
            heatindex_f: 66.4,
            dewpoint_c: 10.5,
            dewpoint_f: 50.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.9,
            gust_kph: 27.2,
            uv: 5.0,
          },
          {
            time_epoch: 1697014800,
            time: "2023-10-11 10:00",
            temp_c: 20.1,
            temp_f: 68.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 13.0,
            wind_kph: 20.9,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1010.0,
            pressure_in: 29.83,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 55,
            cloud: 33,
            feelslike_c: 20.1,
            feelslike_f: 68.2,
            windchill_c: 20.1,
            windchill_f: 68.2,
            heatindex_c: 20.9,
            heatindex_f: 69.6,
            dewpoint_c: 10.8,
            dewpoint_f: 51.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.8,
            gust_kph: 27.0,
            uv: 6.0,
          },
          {
            time_epoch: 1697018400,
            time: "2023-10-11 11:00",
            temp_c: 21.2,
            temp_f: 70.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 13.4,
            wind_kph: 21.6,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1010.0,
            pressure_in: 29.81,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 28,
            feelslike_c: 21.2,
            feelslike_f: 70.2,
            windchill_c: 21.2,
            windchill_f: 70.2,
            heatindex_c: 22.7,
            heatindex_f: 72.9,
            dewpoint_c: 11.1,
            dewpoint_f: 52.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.8,
            gust_kph: 27.0,
            uv: 6.0,
          },
          {
            time_epoch: 1697022000,
            time: "2023-10-11 12:00",
            temp_c: 22.2,
            temp_f: 71.9,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 14.1,
            wind_kph: 22.7,
            wind_degree: 232,
            wind_dir: "SW",
            pressure_mb: 1009.0,
            pressure_in: 29.79,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 50,
            cloud: 23,
            feelslike_c: 24.5,
            feelslike_f: 76.0,
            windchill_c: 22.2,
            windchill_f: 71.9,
            heatindex_c: 24.5,
            heatindex_f: 76.0,
            dewpoint_c: 11.4,
            dewpoint_f: 52.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 16.8,
            gust_kph: 27.1,
            uv: 6.0,
          },
          {
            time_epoch: 1697025600,
            time: "2023-10-11 13:00",
            temp_c: 22.0,
            temp_f: 71.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 14.5,
            wind_kph: 23.4,
            wind_degree: 231,
            wind_dir: "SW",
            pressure_mb: 1008.0,
            pressure_in: 29.77,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 52,
            cloud: 45,
            feelslike_c: 24.5,
            feelslike_f: 76.1,
            windchill_c: 22.0,
            windchill_f: 71.6,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 17.7,
            gust_kph: 28.4,
            uv: 5.0,
          },
          {
            time_epoch: 1697029200,
            time: "2023-10-11 14:00",
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            wind_mph: 15.0,
            wind_kph: 24.1,
            wind_degree: 231,
            wind_dir: "SW",
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 53,
            cloud: 68,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 11.7,
            dewpoint_f: 53.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 18.6,
            gust_kph: 29.9,
            uv: 6.0,
          },
          {
            time_epoch: 1697032800,
            time: "2023-10-11 15:00",
            temp_c: 21.5,
            temp_f: 70.8,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 15.4,
            wind_kph: 24.8,
            wind_degree: 230,
            wind_dir: "SW",
            pressure_mb: 1006.0,
            pressure_in: 29.72,
            precip_mm: 0.0,
            precip_in: 0.0,
            humidity: 54,
            cloud: 90,
            feelslike_c: 21.5,
            feelslike_f: 70.8,
            windchill_c: 21.5,
            windchill_f: 70.8,
            heatindex_c: 24.4,
            heatindex_f: 76.0,
            dewpoint_c: 11.9,
            dewpoint_f: 53.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10.0,
            vis_miles: 6.0,
            gust_mph: 19.3,
            gust_kph: 31.0,
            uv: 5.0,
          },
          {
            time_epoch: 1697036400,
            time: "2023-10-11 16:00",
            temp_c: 20.7,
            temp_f: 69.3,
            is_day: 1,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/263.png",
              code: 1150,
            },
            wind_mph: 14.8,
            wind_kph: 23.8,
            wind_degree: 235,
            wind_dir: "SW",
            pressure_mb: 1006.0,
            pressure_in: 29.72,
            precip_mm: 0.2,
            precip_in: 0.01,
            humidity: 59,
            cloud: 84,
            feelslike_c: 20.7,
            feelslike_f: 69.3,
            windchill_c: 20.7,
            windchill_f: 69.3,
            heatindex_c: 22.6,
            heatindex_f: 72.7,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 17,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 8.3,
            vis_miles: 5.0,
            gust_mph: 19.2,
            gust_kph: 31.0,
            uv: 5.0,
          },
          {
            time_epoch: 1697040000,
            time: "2023-10-11 17:00",
            temp_c: 19.8,
            temp_f: 67.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 14.3,
            wind_kph: 23.0,
            wind_degree: 239,
            wind_dir: "WSW",
            pressure_mb: 1006.0,
            pressure_in: 29.71,
            precip_mm: 0.3,
            precip_in: 0.01,
            humidity: 64,
            cloud: 79,
            feelslike_c: 19.8,
            feelslike_f: 67.6,
            windchill_c: 19.8,
            windchill_f: 67.6,
            heatindex_c: 20.8,
            heatindex_f: 69.4,
            dewpoint_c: 12.7,
            dewpoint_f: 54.9,
            will_it_rain: 0,
            chance_of_rain: 33,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.7,
            vis_miles: 4.0,
            gust_mph: 19.0,
            gust_kph: 30.6,
            uv: 4.0,
          },
          {
            time_epoch: 1697043600,
            time: "2023-10-11 18:00",
            temp_c: 19.0,
            temp_f: 66.1,
            is_day: 1,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/day/263.png",
              code: 1150,
            },
            wind_mph: 13.6,
            wind_kph: 22.0,
            wind_degree: 244,
            wind_dir: "WSW",
            pressure_mb: 1006.0,
            pressure_in: 29.71,
            precip_mm: 0.52,
            precip_in: 0.02,
            humidity: 69,
            cloud: 73,
            feelslike_c: 19.0,
            feelslike_f: 66.1,
            windchill_c: 19.0,
            windchill_f: 66.1,
            heatindex_c: 19.0,
            heatindex_f: 66.1,
            dewpoint_c: 13.1,
            dewpoint_f: 55.6,
            will_it_rain: 0,
            chance_of_rain: 50,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 5.0,
            vis_miles: 3.0,
            gust_mph: 18.9,
            gust_kph: 30.4,
            uv: 4.0,
          },
          {
            time_epoch: 1697047200,
            time: "2023-10-11 19:00",
            temp_c: 17.0,
            temp_f: 62.6,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 11.6,
            wind_kph: 18.7,
            wind_degree: 279,
            wind_dir: "W",
            pressure_mb: 1007.0,
            pressure_in: 29.72,
            precip_mm: 0.9,
            precip_in: 0.04,
            humidity: 74,
            cloud: 82,
            feelslike_c: 16.6,
            feelslike_f: 61.9,
            windchill_c: 16.6,
            windchill_f: 61.9,
            heatindex_c: 17.0,
            heatindex_f: 62.6,
            dewpoint_c: 12.3,
            dewpoint_f: 54.1,
            will_it_rain: 0,
            chance_of_rain: 51,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 6.3,
            vis_miles: 3.0,
            gust_mph: 15.9,
            gust_kph: 25.6,
            uv: 1.0,
          },
          {
            time_epoch: 1697050800,
            time: "2023-10-11 20:00",
            temp_c: 15.0,
            temp_f: 59.0,
            is_day: 0,
            condition: {
              text: "Patchy light drizzle",
              icon: "//cdn.weatherapi.com/weather/64x64/night/263.png",
              code: 1150,
            },
            wind_mph: 9.8,
            wind_kph: 15.8,
            wind_degree: 314,
            wind_dir: "NW",
            pressure_mb: 1007.0,
            pressure_in: 29.74,
            precip_mm: 1.3,
            precip_in: 0.05,
            humidity: 80,
            cloud: 91,
            feelslike_c: 14.2,
            feelslike_f: 57.6,
            windchill_c: 14.2,
            windchill_f: 57.6,
            heatindex_c: 15.0,
            heatindex_f: 59.0,
            dewpoint_c: 11.5,
            dewpoint_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 52,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 7.7,
            vis_miles: 4.0,
            gust_mph: 13.0,
            gust_kph: 20.9,
            uv: 1.0,
          },
          {
            time_epoch: 1697054400,
            time: "2023-10-11 21:00",
            temp_c: 13.0,
            temp_f: 55.4,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 7.8,
            wind_kph: 12.6,
            wind_degree: 350,
            wind_dir: "N",
            pressure_mb: 1008.0,
            pressure_in: 29.76,
            precip_mm: 1.75,
            precip_in: 0.07,
            humidity: 86,
            cloud: 100,
            feelslike_c: 11.9,
            feelslike_f: 53.4,
            windchill_c: 11.9,
            windchill_f: 53.4,
            heatindex_c: 13.0,
            heatindex_f: 55.4,
            dewpoint_c: 10.7,
            dewpoint_f: 51.2,
            will_it_rain: 0,
            chance_of_rain: 53,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.0,
            vis_miles: 5.0,
            gust_mph: 10.0,
            gust_kph: 16.2,
            uv: 1.0,
          },
          {
            time_epoch: 1697058000,
            time: "2023-10-11 22:00",
            temp_c: 12.3,
            temp_f: 54.1,
            is_day: 0,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 8.9,
            wind_kph: 14.4,
            wind_degree: 344,
            wind_dir: "NNW",
            pressure_mb: 1009.0,
            pressure_in: 29.78,
            precip_mm: 1.2,
            precip_in: 0.05,
            humidity: 83,
            cloud: 97,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            windchill_c: 10.8,
            windchill_f: 51.4,
            heatindex_c: 12.3,
            heatindex_f: 54.1,
            dewpoint_c: 9.6,
            dewpoint_f: 49.3,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.3,
            vis_miles: 5.0,
            gust_mph: 11.4,
            gust_kph: 18.4,
            uv: 1.0,
          },
          {
            time_epoch: 1697061600,
            time: "2023-10-11 23:00",
            temp_c: 11.6,
            temp_f: 52.9,
            is_day: 0,
            condition: {
              text: "Light rain",
              icon: "//cdn.weatherapi.com/weather/64x64/night/296.png",
              code: 1183,
            },
            wind_mph: 10.1,
            wind_kph: 16.2,
            wind_degree: 337,
            wind_dir: "NNW",
            pressure_mb: 1009.0,
            pressure_in: 29.8,
            precip_mm: 0.6,
            precip_in: 0.02,
            humidity: 81,
            cloud: 94,
            feelslike_c: 9.7,
            feelslike_f: 49.5,
            windchill_c: 9.7,
            windchill_f: 49.5,
            heatindex_c: 11.6,
            heatindex_f: 52.9,
            dewpoint_c: 8.4,
            dewpoint_f: 47.1,
            will_it_rain: 0,
            chance_of_rain: 67,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9.7,
            vis_miles: 6.0,
            gust_mph: 12.8,
            gust_kph: 20.5,
            uv: 1.0,
          },
        ],
      },
    ],
  },
};

export default defaultWeatherData;
